apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginSitemap-Custom
spec:
  enabled: true
  version: 1.0.3
  requires: ">=2.0.0"
  author:
    name: Halo OSS Team, Carol
    website: https://github.com/halo-dev, https://blog.cnkj.site/
  logo: https://blog.cnkj.site/upload/sitemap.jpg
  homepage: https://redirect.cnkj.site:18092/gitea/plugin-sitemap
  displayName: "Sitemap"
  description: "为站点生成站点地图"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-sigs/plugin-sitemap/blob/main/LICENSE"
